### ISSUE TITLE
Разобраться Почему пластиковый реперный диск работает

### ISSUE THREAD

**Issue by vlasival** [dvi-joke/dvijoke-main#1]
https://www.ozon.ru/product/repernyy-disk-58-zubov-2-propuska-bez-protochki-memz-968-1493178218/?asb=6Y47ClfDKCeZPS%252BUeswPVpyrY77y0h2kNlgXg1usajg%253D&asb2=z2Rg3o_M1JVZniHSFXSy7ReJAzAQN1fFnmVXeZtUQo-PqozLN86pyKWSC6GEQTjS&avtc=1&avte=2&avts=1726723812&keywords=%D1%80%D0%B5%D0%BF%D0%B5%D1%80%D0%BD%D1%8B%D0%B9+%D0%B4%D0%B8%D1%81%D0%BA

**Comment by AlohaKuino** [comment]
сам подписал
деловой

**Comment by vlasival** [comment]
Для работы индукционного ДПКВ необходим металлический реперный диск, поскольку пластик не может создать переменное магнитное поле для индукции напряжения. Однако, датчики Холла могут использовать магнитные метки на пластиковом диске или встроенные магниты в диск для считывания положения. В таком случае пластиковый реперный диск может быть использован, если он снабжен нужными магнитами, способными взаимодействовать с датчиком Холла.
